### ISSUE TITLE
Error while taking off causes the ship to be stuck "waiting to land"

### ISSUE THREAD

**Issue by Zaggy1024** [Zaggy1024/LC_OpenBodyCams#19]
From @ManGuyNY https://github.com/Zaggy1024/LC_OpenBodyCams/issues/13#issuecomment-1943063481

> Now having a different issue that seems to occur when a player dies and the ship takes off. I get softlocked with "Wait for ship to land" but it never does. OpenBodyCams had some errors in the console, but they unfortunately did not get saved to the log T-T. I'll post them here, straight from the console, if I can reproduce the issue again.

**Comment by ManGuyNY** [comment]
I was able to trigger it again.

 `[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OpenBodyCams.BodyCamComponent.SetTargetToPlayer (GameNetcodeStuff.PlayerControllerB player) (at <63aef440f28e47c2a7b3da652a7498ef>:IL_01EC)
OpenBodyCams.SyncBodyCamToRadarMap.UpdateBodyCamTarget () (at <63aef440f28e47c2a7b3da652a7498ef>:IL_0013)
OpenBodyCams.SyncBodyCamToRadarMap+<>c.<UpdateBodyCamTargetForMap>b__8_0 (OpenBodyCams.SyncBodyCamToRadarMap syncedCam) (at <63aef440f28e47c2a7b3da652a7498ef>:IL_0000)
OpenBodyCams.SyncBodyCamToRadarMap.DoForMap (ManualCameraRenderer mapRenderer, System.Action`1[T] action) (at <63aef440f28e47c2a7b3da652a7498ef>:IL_0017)
OpenBodyCams.SyncBodyCamToRadarMap.UpdateBodyCamTargetForMap (ManualCameraRenderer mapRenderer) (at <63aef440f28e47c2a7b3da652a7498ef>:IL_0000)
OpenBodyCams.Patches.PatchManualCameraRenderer.SwitchScreenOnPostfix (ManualCameraRenderer __instance) (at <63aef440f28e47c2a7b3da652a7498ef>:IL_000F)
(wrapper dynamic-method) ManualCameraRenderer.DMD<ManualCameraRenderer::SwitchScreenOn>(ManualCameraRenderer,bool)
StartOfRound.SwitchMapMonitorPurpose (System.Boolean displayInfo) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0044)
StartOfRound+<EndOfGame>d__260.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_01E7)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

I was able to reproduce it by loading up this seed: 67694039 on the Telamon mansion map and having the guest get killed by the Herobrine mod while the host sits in the ship. After the guest is killed, their cam goes blank and attempting to depart the planet soft locks the game as described in my earlier post. 

Wondering if this could be related to the player getting killed in ways caused by other mods that are unexpected by this one. The Herobrine mod specifically replaces the dead body with a custom model. I believe this has also happened to me when a player gets killed by the mimic fire exit, but I would have to do further testing to confirm that.

Mod code: 018da60b-e8b3-f894-259d-f04495332494

**Comment by Zaggy1024** [comment]
I wasn't able to find a way to test Herobrine, since it doesn't show up as a spawnable enemy, but I have a pretty strong hunch that this was the issue. Please let me know here if you encounter this specific issue again (otherwise open a new issue), and I'll reopen this and try to investigate further.
