### ISSUE TITLE
Monitor resolution doesn't seem to do anything

### ISSUE THREAD

**Issue by DeathWrench** [Zaggy1024/LC_OpenBodyCams#20]
![image](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/45341450/61e3431e-cafe-4221-a966-f99a5fbbd3e5)
Will update my modpack here in a bit.

**Comment by Zaggy1024** [comment]
It looks like the resolution is higher than the default, so I'm gonna need more information than that screenshot to know what the problem here is.

**Comment by DeathWrench** [comment]
Here is the [modpack](https://thunderstore.io/c/lethal-company/p/DeathWrench/BestestModpack/) v1.0.9, it includes configs as well.

**Comment by Zaggy1024** [comment]
I need a proper description of the issue you encountered as well, since the screenshot you showed appears to display a non-default resolution on the body cam.

**Comment by DeathWrench** [comment]
![image](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/45341450/9343368c-d753-4151-987e-e882aab8ea5c)

**Comment by Zaggy1024** [comment]
This is caused by [FixResolution](https://thunderstore.io/c/lethal-company/p/nodelll/kruumys_FixResolution/) doing a very stupid thing. It's overriding the resolution of every single camera in the entire game, rather than just targeting the gameplay cameras of the players in the game. I don't believe the gameplay cameras' texture sizes even change, so there's literally no reason to do it this way.

Also, why install that mod as well as HDLethalCompany with its resolution setting cranked up to 2.977?

**Comment by DeathWrench** [comment]
The reason: I forgot I had FixResolution!
