### ISSUE TITLE
Ship Lights Flicker While Using Helmet Visor Remover Mods

### ISSUE THREAD

**Issue by DjTust** [Zaggy1024/LC_OpenBodyCams#29]
Easily replicable, use any mod that removes the helmet visor while having this mods framerate option set to anything lower than game client's fps excluding 0. Need to be looking in the general direction of the monitor for it to happen. Didn't seem to occur when game fps cap was set to 30. Tested in otherwise vanilla profiles with several different visor removers. One example - 018dd2e5-c266-c8eb-1b39-f4a0f1e6340f

I also noticed that a different mod, [Helmet Cameras](https://thunderstore.io/c/lethal-company/p/RickArg/Helmet_Cameras/), also had this issue since it’s mentioned as being fixed in its 2.1.2 version changelog. https://github.com/The0therOne/Helmet_Cameras/issues/5

https://github.com/Zaggy1024/LC_OpenBodyCams/assets/160939125/e78e29aa-66de-4412-9f2a-db96a9f67782

**Comment by Zaggy1024** [comment]
Ah yes, this issue is something I've seen already. It actually still happens with Helmet_Cameras, but on the helmet camera instead of the player's camera.

I can potentially make it so that my mod does the same thing, but I don't quite consider that a solution.

The reason why this happens eludes me somewhat, but it's related to a plane that's attached to the visor that gets hidden when these mods disable the visor. Making that plane invisible also causes the sky to be visible through the fog on Dine, Rend and Titan, from my experience, so anything outdoors will be silhouetted.

I do have more tools at my disposal now to maybe get to the bottom of this, and I have a theory of what might help, but I can't promise anything.

**Comment by DeathWrench** [comment]
I only know of 3 mods to remove the visor 
- [RemoveMotionSway](https://thunderstore.io/c/lethal-company/p/kz/RemoveMotionSway) 
- [Visorless](https://thunderstore.io/c/lethal-company/p/ChubbzCrew/Visorless/)
- [DisablePostProcessing](https://thunderstore.io/c/lethal-company/p/Woowz11/DisablePostprocessing)
I recently made a mod that also does this: [DisableHelmetVisor](https://thunderstore.io/c/lethal-company/p/DeathWrench/DisableHelmetVisor), it's based off of [DisablePostProcessing](https://thunderstore.io/c/lethal-company/p/Woowz11/DisablePostprocessing) so if you tried it then you tried this. Idk which ones you've tried but it might be helpful to know since the method of removing the visor is different for those 3.

**Comment by DjTust** [comment]
I don't think that particular mod came up when I was searching for visor mods, so I only know that the first method causes the issue. I'll test your mod and disablepostprocessing when I next get a chance.

**Comment by ChloeDawn** [comment]
This issue also occurs without any visor removal mods simply when spectating a player whilst the body camera is being rendered on screen.

**Comment by Zaggy1024** [comment]
That would make sense to me, since the spectator camera often has issues with that plane not appearing and causing the fog to be less visible than intended on the foggy moons.

I still have yet to look deeper into this sometime. I have a theory that if I clone the custom pass that the main camera uses, it'll stop having this issue, but if that doesn't work then I'll have to try to understand how the fog, that custom pass and the plane attached to the camera all interact.

**Comment by Zaggy1024** [comment]
I wasn't able to reproduce this issue exactly as described on v62 and OpenBodyCams 2.2.4, possibly due to 6966013. In those recent versions, the flickering instead occurs on the body cam screen, rather than the gameplay camera. That flickering has been resolved in the commit linked above, so if you still encounter this issue, please let me know how I can reproduce it with version 2.3.0.
