### ISSUE TITLE
Door cam freeze bug? *Suggestion Included*

### ISSUE THREAD

**Issue by HE70v** [Zaggy1024/LC_OpenBodyCams#3]
I don't believe this is intentional but more so as a result of the optimization implemented.

The front door camera seems to freeze/stop updating when you're not looking toward the body cam monitor whilst in the ship. This can make it difficult for people like me to see if the eyeless dogs in the front of the ship are dead after smacking at the door with a shovel.
 
![Cam Freeze](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/157659896/cae315b2-3552-4277-a2c8-85aad7bfa458)
*Suggestion*
-You should try to implement a static camera option for the radar booster like how it is in the "Helmet Cameras" mod by RickArg.
-As well as an option to toggle the front door camera between its original camera, body camera, and off.

**Comment by Zaggy1024** [comment]
The body cam appearing near the door is actually just an oversight on my part, I hadn't considered that the material for those two screens is shared and I never checked. I'll hopefully have a fix out for that soon.

The reason it pauses is indeed an optimization, it's assuming that nothing is viewing the body cam except the monitor at the front of the ship. For the sake of some mods, I may have to make an option to disable that.

Swapping between body cam and external security cam isn't a bad idea, but probably not on my todo list since it's a pretty niche use case (unless others chime in asking for it).

**Comment by HE70v** [comment]
W updates nicely done

**Comment by Zaggy1024** [comment]
Thanks!

**Comment by Zaggy1024** [comment]
> -You should try to implement a static camera option for the radar booster like how it is in the "Helmet Cameras" mod by RickArg.

With regard to this, feel free to open an issue to track that suggestion.
