### ISSUE TITLE
[Request] store purchasing for body cams

### ISSUE THREAD

**Issue by ajsglist** [Zaggy1024/LC_OpenBodyCams#33]
it would be great if there was an option to make the body cams a purchasable ship upgrade

thanks for the consideration

**Comment by Zaggy1024** [comment]
Oh, I forgot to reply to this when I saw it a while ago, but this will be in the upcoming version.

**Comment by DeterminedPanda** [comment]
changing default behaviour and then hiding the option to restore the default behaviour deep inside of the config. what an absolute home run.

**Comment by Zaggy1024** [comment]
> changing default behaviour and then hiding the option to restore the default behaviour deep inside of the config. what an absolute home run.

I definitely should have handled that change better. I had taken a poll in the modding Discord server, which is the only place I know of that people would have seen such a thing, and the majority of people preferred it to be the new default.

However, I should have thought to put a tip in the game sooner than a minor release after 2.0.0, so that people could change the option immediately if desired, so I understand your frustration if your issue was that you had no way of knowing about the change.

The reason I lean towards making this the default mode is that I doubt it's most end users' tendencies to check changelogs and config files, so the ship upgrade feature would have remained largely undiscovered, which I would imagine has happened with the picture-in-picture feature as well. Conversely, not seeing the body cam on the monitor upon loading in would make the mod appear non-functional, so that notification upon installing the update was vital.

(You say "deep inside the config", but I don't know that I could have made it more obvious that it's there. r2modman sorts the config categories alphabetically, so my ordering doesn't matter for that. I'm not exactly sure where you would have expected that option to be.)

**Comment by Zaggy1024** [comment]
Closing this now since the feature is complete, but feel free to create any issues if you have suggestions to improve the migration experience.
