### ISSUE TITLE
"NightVisionBrightness" setting not working in the facility when "CullFactory" is installed

### ISSUE THREAD

**Issue by dounai2333** [Zaggy1024/LC_OpenBodyCams#35]
I have set "NightVisionBrightness" to 10, and this setting only take affect when player is outside the facility, after player enter the facility, the body cam will show the actual vision.

**Comment by Zaggy1024** [comment]
Is the issue that night vision is too bright in the interior, and do you have CullFactory? If so, it's likely a conflict with CullFactory that's causing your issue, since its method for hiding lights conflicts with OpenBodyCams currently. I have a fix for this in OpenBodyCams locally, and I'll include it in the next release.

**Comment by dounai2333** [comment]
Yes I have CullFactory installed, since there is not much mods that can increase the framerate without make game looks like potato.
After uninstall CullFactory it works now, thanks for letting me know!
<details><summary>Screenshot:</summary>

![monitor](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/45044404/c1e8c153-6b12-4cea-bc23-a39d077032ac)

![inside player](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/45044404/d51da2fd-9ad6-4a1c-b5fb-d65d3f99d8dc)
</details>

**Comment by Zaggy1024** [comment]
Should be fixed in 2.0.0!
