### ISSUE TITLE
[Bug] Teleported Radar Boosters never turn on their cameras

### ISSUE THREAD

**Issue by zndrmn** [Zaggy1024/LC_OpenBodyCams#37]
With this setting set to `DisableCameraWhileTargetIsOnShip = true`, radar boosters that are teleported outside of the ship will always have their cameras disabled. Switching targets doesn't fix it.

I'm using [EnhancedRadarBooster](https://thunderstore.io/c/lethal-company/p/MrHydralisk/EnhancedRadarBooster/) to teleport the radar booster with the teleporter.

**Comment by Zaggy1024** [comment]
This has been an issue for a while, and there's no solution I'd like to implement for it on my side. The problem is that [EnhancedRadarBooster doesn't mark its teleportation target's flags to indicate whether it's in the ship, nor whether it's in the interior](https://github.com/MrHydralisk/Lethal-Company-Enhanced-Radar-Booster/blob/main/EnhancedRadarBooster/EnhancedRadarBoosterNetworkHandler.cs#L54-L62). If the mod is maintained still, then I would suggest you bring it up in their issue tracker.

**Comment by zndrmn** [comment]
Mkay I'll report this to EnhancedRadarBooster's repo and link this issue there

**Comment by MrHydralisk** [comment]
> The problem is that EnhancedRadarBooster doesn't mark its teleportation target's flags to indicate whether it's in the ship, nor whether it's in the interior.

If can tell me what command call and changes that flag state that you need, then can fix it faster.

**Comment by Zaggy1024** [comment]
The particular one that is important is `GrabbableObject.isInShipRoom`, but every field that is relevant to the position of the item needs to be updated:
- `GrabbableObject.isInElevator`
- `GrabbableObject.isInShipRoom`
- `GrabbableObject.isInFactory`

If I remember right, there may have also been an issue with the radar booster not working after a teleport due to `RadarBoosterItem.radarEnabled` and `GrabbableObject.isBeingUsed` becoming mismatched.

**Comment by MrHydralisk** [comment]
Should have no issues now in v.1.7.0
