### ISSUE TITLE
[Request] Config option to indicate "disabled cams"

### ISSUE THREAD

**Issue by ajsglist** [Zaggy1024/LC_OpenBodyCams#38]
We've been trying to use the "disable cams on ship" option to keep resource usage down for our players with weaker computers.  One common concern, however, is that the bodycam shutoff is pretty jarring when cycling through players.  It's also a bit weird for a monitor to simply be blank.

We would love if there was a config option to display some sort of message about the disconnected bodycam or the on-ship location of the target.

It would be even more amazing if the monitor texture is configurable and can be pointed to a custom texture (similar to LethalPosters, CustomPaintings, CustomDeathAudio implementations)

Thanks for the consideration

**Comment by ajsglist** [comment]
This seems to more-or-less have been addressed with the recent update, so I'm going to close this one out :)

**Comment by Zaggy1024** [comment]
Ah, thanks for closing this out. I actually thought I had replied to this before, so sorry that I actually never did.

I kinda had this at the back of my mind for a long time, but the unreadability of the ship upgrade really pushed me to figure out how to do the overlay. Had I actually remembered to reply here, I would've mentioned that it's deceptively complicated to implement, but thankfully I found a satisfactory way to do so after a lot of thinking on and off about it. 

Since you also mentioned adding images to use as a placeholder, feel free to file an issue for that if you still would like to see it implemented.
