### ISSUE TITLE
The mod breaks compatibility with LethalLib when updated to 2.0+

### ISSUE THREAD

**Issue by DLumi** [Zaggy1024/LC_OpenBodyCams#44]
When OpenBodyCams are updated past v2.0, the mod stops displaying cameras on the monitor when LethalLib is enabled.

**Comment by Zaggy1024** [comment]
If you want the body cams to be enabled by default, you can go into the config and disable the ship upgrade. LethalLib is a soft dependency to implement the ship upgrade.

Admittedly, I made a bit of a mistake enabling that by default, since it did cause a bit of confusion. However if you upgraded to 2.0.4+, you should have been given an in-game tip upon loading into a save to tell you that it is now a ship upgrade unless the config option is changed.
